### ISSUE TITLE
Why is there a limit on the number of secrets?

### ISSUE THREAD

**Issue by sadasant** [actions/workflow-parser#31]
Hi! I'm just passing by, reading source code. Good job so far! The code is super clean. I hope this comes as a compliment, specially since I have nothing to do with your team and I was able to follow it thoroughly pretty easily! 👏 it makes me happy. Anyway, the question:

I saw that there's a limit on the number of secrets. It got me curious. Is there a reason for this? Or is it just a preemptive measure to the possibility of a memory overflow attack?
https://github.com/actions/workflow-parser/blob/master/parser/parser.go#L152

Anyway, feel free to close this issue! Thanks for your time and keep up the good work! :) I'm sure there are many like me that are quite excited about *actions*. 🙌

**Comment by piki** [comment]
@sadasant Thanks for your kind words.

The limit on the number of secrets is imposed by the key-management backend software we are using.  We might relax the limit if the implementation changes.

I do hope the current limit, 100, is enough for most use cases.

**Comment by sadasant** [comment]
@piki thank you for your response! I understand. Take care!
