### ISSUE TITLE
actions/reviewers (codeowners) not visible

### ISSUE THREAD

**Issue by benknoble** [actions/workflow-parser#51]
I visited the link https://github.com/orgs/actions/teams/reviewers from my recent PR (#50), and hit the 404 page.

I'm not sure if this means

- I can't see the people on the team; or
- the team does not exist.

If the team does not exist, who should I ping re: #50 and could CODEOWNERS be corrected?

**Comment by parkr** [comment]
The team exists, but it's presently marked as "Secret". 👍
